# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/winston/Projects/C/Mashtasic-C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/winston/Projects/C/Mashtasic-C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/winston/Projects/C/Mashtasic-C/CMakeFiles /home/winston/Projects/C/Mashtasic-C//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/winston/Projects/C/Mashtasic-C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nanopb

# Build rule for target.
nanopb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanopb
.PHONY : nanopb

# fast build rule for target.
nanopb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/build
.PHONY : nanopb/fast

#=============================================================================
# Target rules for targets named proto

# Build rule for target.
proto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proto
.PHONY : proto

# fast build rule for target.
proto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/build
.PHONY : proto/fast

#=============================================================================
# Target rules for targets named bar

# Build rule for target.
bar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bar
.PHONY : bar

# fast build rule for target.
bar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bar.dir/build.make CMakeFiles/bar.dir/build
.PHONY : bar/fast

extern/firmware/src/mesh/generated/meshtastic/admin.pb.o: extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/admin.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/admin.pb.i: extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/admin.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/admin.pb.s: extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/admin.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/admin.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/apponly.pb.o: extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/apponly.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/apponly.pb.i: extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/apponly.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/apponly.pb.s: extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/apponly.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/apponly.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/atak.pb.o: extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/atak.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/atak.pb.i: extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/atak.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/atak.pb.s: extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/atak.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/atak.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.o: extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.i: extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.s: extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/channel.pb.o: extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/channel.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/channel.pb.i: extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/channel.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/channel.pb.s: extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/channel.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/channel.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.o: extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.i: extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.s: extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/config.pb.o: extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/config.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/config.pb.i: extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/config.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/config.pb.s: extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/config.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/config.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.o: extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.i: extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.s: extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.o: extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.i: extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.s: extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.o: extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.i: extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.s: extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.o: extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.i: extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.s: extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/localonly.pb.o: extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/localonly.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/localonly.pb.i: extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/localonly.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/localonly.pb.s: extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/localonly.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/localonly.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/mesh.pb.o: extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mesh.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/mesh.pb.i: extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mesh.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/mesh.pb.s: extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mesh.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mesh.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/module_config.pb.o: extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/module_config.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/module_config.pb.i: extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/module_config.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/module_config.pb.s: extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/module_config.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/module_config.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.o: extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.i: extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.s: extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.o: extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.i: extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.s: extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/portnums.pb.o: extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/portnums.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/portnums.pb.i: extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/portnums.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/portnums.pb.s: extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/portnums.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/portnums.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/powermon.pb.o: extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/powermon.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/powermon.pb.i: extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/powermon.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/powermon.pb.s: extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/powermon.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/powermon.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.o: extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.i: extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.s: extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.o: extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.i: extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.s: extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.o: extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.i: extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.s: extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.o: extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.i: extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.s: extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.cpp.s

extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.o: extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.o

# target to build an object file
extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.o
.PHONY : extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.o

extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.i: extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.i

# target to preprocess a source file
extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.i
.PHONY : extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.i

extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.s: extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.s

# target to generate assembly for a file
extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proto.dir/build.make CMakeFiles/proto.dir/extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.s
.PHONY : extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.cpp.s

home/winston/Junk/build/nanopb/pb_common.o: home/winston/Junk/build/nanopb/pb_common.c.o
.PHONY : home/winston/Junk/build/nanopb/pb_common.o

# target to build an object file
home/winston/Junk/build/nanopb/pb_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/home/winston/Junk/build/nanopb/pb_common.c.o
.PHONY : home/winston/Junk/build/nanopb/pb_common.c.o

home/winston/Junk/build/nanopb/pb_common.i: home/winston/Junk/build/nanopb/pb_common.c.i
.PHONY : home/winston/Junk/build/nanopb/pb_common.i

# target to preprocess a source file
home/winston/Junk/build/nanopb/pb_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/home/winston/Junk/build/nanopb/pb_common.c.i
.PHONY : home/winston/Junk/build/nanopb/pb_common.c.i

home/winston/Junk/build/nanopb/pb_common.s: home/winston/Junk/build/nanopb/pb_common.c.s
.PHONY : home/winston/Junk/build/nanopb/pb_common.s

# target to generate assembly for a file
home/winston/Junk/build/nanopb/pb_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/home/winston/Junk/build/nanopb/pb_common.c.s
.PHONY : home/winston/Junk/build/nanopb/pb_common.c.s

home/winston/Junk/build/nanopb/pb_decode.o: home/winston/Junk/build/nanopb/pb_decode.c.o
.PHONY : home/winston/Junk/build/nanopb/pb_decode.o

# target to build an object file
home/winston/Junk/build/nanopb/pb_decode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/home/winston/Junk/build/nanopb/pb_decode.c.o
.PHONY : home/winston/Junk/build/nanopb/pb_decode.c.o

home/winston/Junk/build/nanopb/pb_decode.i: home/winston/Junk/build/nanopb/pb_decode.c.i
.PHONY : home/winston/Junk/build/nanopb/pb_decode.i

# target to preprocess a source file
home/winston/Junk/build/nanopb/pb_decode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/home/winston/Junk/build/nanopb/pb_decode.c.i
.PHONY : home/winston/Junk/build/nanopb/pb_decode.c.i

home/winston/Junk/build/nanopb/pb_decode.s: home/winston/Junk/build/nanopb/pb_decode.c.s
.PHONY : home/winston/Junk/build/nanopb/pb_decode.s

# target to generate assembly for a file
home/winston/Junk/build/nanopb/pb_decode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/home/winston/Junk/build/nanopb/pb_decode.c.s
.PHONY : home/winston/Junk/build/nanopb/pb_decode.c.s

home/winston/Junk/build/nanopb/pb_encode.o: home/winston/Junk/build/nanopb/pb_encode.c.o
.PHONY : home/winston/Junk/build/nanopb/pb_encode.o

# target to build an object file
home/winston/Junk/build/nanopb/pb_encode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/home/winston/Junk/build/nanopb/pb_encode.c.o
.PHONY : home/winston/Junk/build/nanopb/pb_encode.c.o

home/winston/Junk/build/nanopb/pb_encode.i: home/winston/Junk/build/nanopb/pb_encode.c.i
.PHONY : home/winston/Junk/build/nanopb/pb_encode.i

# target to preprocess a source file
home/winston/Junk/build/nanopb/pb_encode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/home/winston/Junk/build/nanopb/pb_encode.c.i
.PHONY : home/winston/Junk/build/nanopb/pb_encode.c.i

home/winston/Junk/build/nanopb/pb_encode.s: home/winston/Junk/build/nanopb/pb_encode.c.s
.PHONY : home/winston/Junk/build/nanopb/pb_encode.s

# target to generate assembly for a file
home/winston/Junk/build/nanopb/pb_encode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanopb.dir/build.make CMakeFiles/nanopb.dir/home/winston/Junk/build/nanopb/pb_encode.c.s
.PHONY : home/winston/Junk/build/nanopb/pb_encode.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bar.dir/build.make CMakeFiles/bar.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bar.dir/build.make CMakeFiles/bar.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bar.dir/build.make CMakeFiles/bar.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/serial_interface.o: src/serial_interface.cpp.o
.PHONY : src/serial_interface.o

# target to build an object file
src/serial_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bar.dir/build.make CMakeFiles/bar.dir/src/serial_interface.cpp.o
.PHONY : src/serial_interface.cpp.o

src/serial_interface.i: src/serial_interface.cpp.i
.PHONY : src/serial_interface.i

# target to preprocess a source file
src/serial_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bar.dir/build.make CMakeFiles/bar.dir/src/serial_interface.cpp.i
.PHONY : src/serial_interface.cpp.i

src/serial_interface.s: src/serial_interface.cpp.s
.PHONY : src/serial_interface.s

# target to generate assembly for a file
src/serial_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bar.dir/build.make CMakeFiles/bar.dir/src/serial_interface.cpp.s
.PHONY : src/serial_interface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bar"
	@echo "... nanopb"
	@echo "... proto"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/admin.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/admin.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/admin.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/apponly.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/apponly.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/apponly.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/atak.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/atak.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/atak.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/cannedmessages.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/channel.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/channel.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/channel.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/clientonly.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/config.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/config.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/config.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/connection_status.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/device_ui.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/deviceonly.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/interdevice.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/localonly.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/localonly.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/localonly.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/mesh.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/mesh.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/mesh.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/module_config.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/module_config.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/module_config.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/mqtt.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/paxcount.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/portnums.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/portnums.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/portnums.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/powermon.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/powermon.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/powermon.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/remote_hardware.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/rtttl.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/storeforward.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/telemetry.pb.s"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.o"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.i"
	@echo "... extern/firmware/src/mesh/generated/meshtastic/xmodem.pb.s"
	@echo "... home/winston/Junk/build/nanopb/pb_common.o"
	@echo "... home/winston/Junk/build/nanopb/pb_common.i"
	@echo "... home/winston/Junk/build/nanopb/pb_common.s"
	@echo "... home/winston/Junk/build/nanopb/pb_decode.o"
	@echo "... home/winston/Junk/build/nanopb/pb_decode.i"
	@echo "... home/winston/Junk/build/nanopb/pb_decode.s"
	@echo "... home/winston/Junk/build/nanopb/pb_encode.o"
	@echo "... home/winston/Junk/build/nanopb/pb_encode.i"
	@echo "... home/winston/Junk/build/nanopb/pb_encode.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/serial_interface.o"
	@echo "... src/serial_interface.i"
	@echo "... src/serial_interface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

